services:

    nginx:
        build: "./docker/nginx"
        container_name: nginx
        restart: always
        volumes:
            - ./docker/nginx/conf/:/etc/nginx/conf.d/
            - ./docker/nginx/log/:/var/log/nginx/
        ports:
            - 80:80
            
    node:
        build: "./docker/node"
        container_name: node
        restart: always
        volumes:
            - ./src/:/usr/src/
        ports:
            - 3000:3000
        tty: true
        stdin_open: true
        command: >
            bash -c "nodemon app.js"

    mysql: 
        build: "./docker/mysql"
        container_name: mysql
        restart: always
        volumes: 
            - ./docker/mysql/data/:/docker-entrypoint-initdb.d/
            - ./docker/mysql/conf/:/etc/mysql/conf.d/
        ports: 
            - 3306:3306